language: node_js
node_js:
- 10.16.0
after_success: 
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls

cache:
  directories:
  - node_modules

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
