language: node_js

sudo: required

dist: trusty

node_js:
- "10"

after_success: 
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls

cache:
  directories:
  - node_modules

addons:
  postgresql: "10.6"

apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - node server/services/config.js
  - ./cc-test-reporter before-build

script: "npm run test"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: 
  - npm run coverage