language: node_js
node_js:
- 10.16.0
after_success: 
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls

cache:
  directories:
  - node_modules

services:
  - postgresql

addons:
  postgresql: "10.6"

apt:
    packages:
    - postgresql-10
    - postgresql-client-10