language: node_js
node_js:
- 10.16.0
after_success: 
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls

cache:
  directories:
  - node_modules

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE AutoMart_test;" -U postgres
  - psql -c "CREATE USER chidichuks WITH PASSWORD '1battalion';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cp config/database.yml.travis config/database.yml

script:
  - "npm run nyc"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
